# Generated by Django 3.1.1 on 2020-09-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('tiny_url', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'URL Shortner',
                'verbose_name_plural': 'URLs Shortner',
            },
        ),
    ]
